nohup: ignoring input
wandb: Currently logged in as: xuanzhu_07 (xuanzhu_07-university-of-sydney). Use `wandb login --relogin` to force relogin
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: ERROR Error while calling W&B API: run "m1m7e4yt" not found while updating run (<Response [404]>)
wandb: / Waiting for wandb.init()...Problem at: /home/yxma/hzx/hzx/rand_defence/train.py 86 main
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/yxma/hzx/hzx/rand_defence/train.py", line 413, in <module>
    main()
  File "/home/yxma/hzx/hzx/rand_defence/train.py", line 86, in main
    wandb.init(project='4pointMask', config=args)
  File "/home/yxma/anaconda3/envs/py39_torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    raise e
  File "/home/yxma/anaconda3/envs/py39_torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/yxma/anaconda3/envs/py39_torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
